services:
  - type: web
    name: techhub
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m gunicorn --chdir backend -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
